//
// Created by florianfrank on 29.12.20.
//

#ifndef PIL_ERROR_CODE_DEFINES_H
#define PIL_ERROR_CODE_DEFINES_H

#include <stdint.h>

#define MAX_ERROR_MSG_LEN 128

enum
{
    PIL_NO_ERROR, PIL_INVALID_ARGUMENTS, PIL_ERRNO,

    /* Socket errors */
    PIL_SOCKET_TIMEOUT, PIL_INTERFACE_CLOSED,

    PIL_INVALID_BAUDRATE,

    PIL_INSUFFICIENT_RESOURCES,

    PIL_INSUFFICIENT_PERMISSIONS,

    // Threading error
    PIL_DEADLOCK_DETECTED, PIL_THREAD_NOT_JOINABLE, PIL_THREAD_NOT_FOUND,

    PIL_ONLY_PARTIALLY_READ_WRITTEN, PIL_NO_SUCH_FILE,

    PIL_UNKNOWN_ERROR,

} typedef PIL_ERROR_CODE;


struct
{
    PIL_ERROR_CODE errorCode;
    uint32_t errnoCode;
    char errorMessage[MAX_ERROR_MSG_LEN];
} typedef PIL_ErrorHandle;

#endif //PIL_ERROR_CODE_DEFINES_H
